-- 027_music_reference_seed.sql
--
-- Seeds hymnal_songs with the Children's Songbook, sourced directly from
-- churchofjesuschrist.org's official title index (fetched letter by
-- letter, 2026-09-04). This is a good-faith, best-effort transcription
-- from the live site, not a verified-perfect copy: a small number of
-- entries where the source's own alphabetical-by-title and
-- alphabetical-by-number views disagreed on a number, or where the same
-- song appears to be indexed under two different first lines, were
-- deliberately left out rather than guessed at. Everything here is easy
-- to correct or add to afterward via the "Music Reference" Table Admin
-- page (add/edit/delete like any other admin table).
--
-- The 1985 Hymnal and Hymns for Home and Church are NOT included in this
-- migration -- see chat: same approach works, but is very fetch-heavy
-- (roughly one page load per letter of the alphabet per collection), and
-- worth confirming before spending that on a fast-growing, not-yet-
-- finalized collection in particular.
--
-- Idempotent: safe to re-run (on conflict do nothing -- won't overwrite
-- an entry you've since corrected, or duplicate one you've kept).
-- Requires 026_hymnal_songs_number_as_text.sql to have run first.

insert into hymnal_songs (songbook, number, title) values
  ('childrens_songbook', '12', 'A Child''s Prayer'),
  ('childrens_songbook', '198a', 'A Happy Family'),
  ('childrens_songbook', '197a', 'A Happy Helper'),
  ('childrens_songbook', '22b', 'A Prayer'),
  ('childrens_songbook', '22', 'A Prayer Song'),
  ('childrens_songbook', '267b', 'A Smile Is like the Sunshine'),
  ('childrens_songbook', '20a', 'A Song of Thanks'),
  ('childrens_songbook', '145a', 'A Special Gift Is Kindness'),
  ('childrens_songbook', '166', 'A Young Man Prepared'),
  ('childrens_songbook', '296', 'Air from Orpheus'),
  ('childrens_songbook', '231', 'All Things Bright and Beautiful'),
  ('childrens_songbook', '86a', 'An Angel Came to Joseph Smith'),
  ('childrens_songbook', '294', 'Andante'),
  ('childrens_songbook', '136', 'As I Have Loved You (Love One Another)'),
  ('childrens_songbook', '247', 'Autumn Day'),
  ('childrens_songbook', '42', 'Away in a Manger'),
  ('childrens_songbook', '100', 'Baptism'),
  ('childrens_songbook', '265', 'Be Happy!'),
  ('childrens_songbook', '62', 'Beautiful Savior'),
  ('childrens_songbook', '232', 'Beauty Everywhere'),
  ('childrens_songbook', '234', 'Because God Loves Me'),
  ('childrens_songbook', '239', 'Because It''s Spring'),
  ('childrens_songbook', '73a', 'Before I Take the Sacrament'),
  ('childrens_songbook', '241a', 'Birds in the Tree'),
  ('childrens_songbook', '118', 'Book of Mormon Stories'),
  ('childrens_songbook', '174', 'Called to Serve'),
  ('childrens_songbook', '9', 'Can a Little Child like Me?'),
  ('childrens_songbook', '16', 'Children All Over the World'),
  ('childrens_songbook', '160', 'Choose the Right Way'),
  ('childrens_songbook', '54', 'Christmas Bells'),
  ('childrens_songbook', '255', 'Come with Me to Primary'),
  ('childrens_songbook', '221', 'Covered Wagons'),
  ('childrens_songbook', '210', 'Daddy''s Homecoming'),
  ('childrens_songbook', '158', 'Dare to Do Right'),
  ('childrens_songbook', '206b', 'Dearest Mother, I Love You'),
  ('childrens_songbook', '64', 'Did Jesus Really Live Again?'),
  ('childrens_songbook', '299', 'Distant Bells'),
  ('childrens_songbook', '276', 'Do As I''m Doing'),
  ('childrens_songbook', '290', 'Each Sunday Morning'),
  ('childrens_songbook', '68', 'Easter Hosanna'),
  ('childrens_songbook', '142', 'Every Star Is Different'),
  ('childrens_songbook', '96', 'Faith'),
  ('childrens_songbook', '248', 'Falling Snow'),
  ('childrens_songbook', '188', 'Families Can Be Together Forever'),
  ('childrens_songbook', '94', 'Family History—I Am Doing It'),
  ('childrens_songbook', '195', 'Family Night'),
  ('childrens_songbook', '189', 'Family Prayer'),
  ('childrens_songbook', '23a', 'Father Up Above'),
  ('childrens_songbook', '29', 'Father, I Will Reverent Be'),
  ('childrens_songbook', '8', 'Father, We Thank Thee for the Night'),
  ('childrens_songbook', '209', 'Fathers'),
  ('childrens_songbook', '282', 'Feliz Cumpleaños'),
  ('childrens_songbook', '110', 'Follow the Prophet'),
  ('childrens_songbook', '21a', 'For Health and Strength'),
  ('childrens_songbook', '21b', 'For Thy Bounteous Blessings'),
  ('childrens_songbook', '262', 'Friends Are Fun'),
  ('childrens_songbook', '253b', 'Fun to Do'),
  ('childrens_songbook', '167', 'Go the Second Mile'),
  ('childrens_songbook', '229', 'God Is Watching Over All'),
  ('childrens_songbook', '97', 'God''s Love'),
  ('childrens_songbook', '200', 'Grandmother'),
  ('childrens_songbook', '80', 'Had I Been a Child'),
  ('childrens_songbook', '264', 'Happy Song'),
  ('childrens_songbook', '284a', 'Happy, Happy Birthday'),
  ('childrens_songbook', '284b', 'Have a Very Happy Birthday!'),
  ('childrens_songbook', '51', 'Have a Very Merry Christmas!'),
  ('childrens_songbook', '65', 'He Died That We Might Live Again'),
  ('childrens_songbook', '34', 'He Sent His Son'),
  ('childrens_songbook', '275a', 'Head, Shoulders, Knees, and Toes'),
  ('childrens_songbook', '280', 'Healthy, Wealthy, and Wise'),
  ('childrens_songbook', '19', 'Heavenly Father, Now I Pray'),
  ('childrens_songbook', '23b', 'Heavenly Father, While I Pray'),
  ('childrens_songbook', '260', 'Hello Song'),
  ('childrens_songbook', '254a', 'Hello, Friends!'),
  ('childrens_songbook', '99', 'Help Me, Dear Father'),
  ('childrens_songbook', '73b', 'Help Us, O God, to Understand'),
  ('childrens_songbook', '261', 'Here We Are Together'),
  ('childrens_songbook', '277', 'Hinges'),
  ('childrens_songbook', '192', 'Home'),
  ('childrens_songbook', '66', 'Hosanna'),
  ('childrens_songbook', '180', 'How Dear to God Are Little Children'),
  ('childrens_songbook', '182', 'How Will They Know?'),
  ('childrens_songbook', '152', 'Hum Your Favorite Hymn'),
  ('childrens_songbook', '2', 'I Am a Child of God'),
  ('childrens_songbook', '151', 'I Am Glad for Many Things'),
  ('childrens_songbook', '163', 'I Am like a Star'),
  ('childrens_songbook', '149', 'I Believe in Being Honest'),
  ('childrens_songbook', '74', 'I Feel My Savior''s Love'),
  ('childrens_songbook', '199', 'I Have a Family Tree'),
  ('childrens_songbook', '269', 'I Have Two Ears'),
  ('childrens_songbook', '272', 'I Have Two Little Hands'),
  ('childrens_songbook', '169', 'I Hope They Call Me on a Mission'),
  ('childrens_songbook', '5', 'I Know My Father Lives'),
  ('childrens_songbook', '104', 'I Like My Birthdays'),
  ('childrens_songbook', '4', 'I Lived in Heaven'),
  ('childrens_songbook', '25b', 'I Love to Pray'),
  ('childrens_songbook', '95', 'I Love to See the Temple'),
  ('childrens_songbook', '18', 'I Need My Heavenly Father'),
  ('childrens_songbook', '202', 'I Often Go Walking'),
  ('childrens_songbook', '161', 'I Pledge Myself to Love the Right'),
  ('childrens_songbook', '14', 'I Pray in Faith'),
  ('childrens_songbook', '7', 'I Thank Thee, Dear Father'),
  ('childrens_songbook', '230', 'I Think the World Is Glorious'),
  ('childrens_songbook', '56', 'I Think When I Read That Sweet Story'),
  ('childrens_songbook', '168', 'I Want to Be a Missionary Now'),
  ('childrens_songbook', '28a', 'I Want to Be Reverent'),
  ('childrens_songbook', '150b', 'I Want to Give the Lord My Tenth'),
  ('childrens_songbook', '148', 'I Want to Live the Gospel'),
  ('childrens_songbook', '271', 'I Wiggle'),
  ('childrens_songbook', '162', 'I Will Be Valiant'),
  ('childrens_songbook', '164', 'I Will Follow God''s Plan'),
  ('childrens_songbook', '28b', 'I Will Try to Be Reverent'),
  ('childrens_songbook', '140', 'I''ll Walk with You'),
  ('childrens_songbook', '150a', 'I''m Glad to Pay a Tithing'),
  ('childrens_songbook', '11', 'I''m Thankful to Be Me'),
  ('childrens_songbook', '78', 'I''m Trying to Be like Jesus'),
  ('childrens_songbook', '15', 'If with All Your Hearts'),
  ('childrens_songbook', '266', 'If You''re Happy'),
  ('childrens_songbook', '288', 'Impromptu'),
  ('childrens_songbook', '291', 'In Quietude'),
  ('childrens_songbook', '240', 'In the Leafy Treetops'),
  ('childrens_songbook', '246', 'It''s Autumntime'),
  ('childrens_songbook', '70', 'Jesus Has Risen'),
  ('childrens_songbook', '58b', 'Jesus Is Our Loving Friend'),
  ('childrens_songbook', '59', 'Jesus Loved the Little Children'),
  ('childrens_songbook', '55', 'Jesus Once Was a Little Child'),
  ('childrens_songbook', '61', 'Jesus Said Love Everyone'),
  ('childrens_songbook', '60', 'Jesus Wants Me for a Sunbeam'),
  ('childrens_songbook', '146', 'Keep the Commandments'),
  ('childrens_songbook', '145b', 'Kindness Begins with Me'),
  ('childrens_songbook', '134', 'Latter-day Prophets'),
  ('childrens_songbook', '252', 'Lift Up Your Voice and Sing'),
  ('childrens_songbook', '107', 'Listen, Listen'),
  ('childrens_songbook', '39', 'Little Jesus'),
  ('childrens_songbook', '58a', 'Little Lambs So White and Fair'),
  ('childrens_songbook', '216', 'Little Pioneer Children'),
  ('childrens_songbook', '244', 'Little Purple Pansies'),
  ('childrens_songbook', '243', 'Little Seeds Lie Fast Asleep'),
  ('childrens_songbook', '190', 'Love Is Spoken Here'),
  ('childrens_songbook', '292a', 'Loving Shepherd'),
  ('childrens_songbook', '44', 'Mary''s Lullaby'),
  ('childrens_songbook', '292b', 'Morning Prayer'),
  ('childrens_songbook', '206a', 'Mother Dear'),
  ('childrens_songbook', '207', 'Mother, I Love You'),
  ('childrens_songbook', '204', 'Mother, Tell Me the Story'),
  ('childrens_songbook', '224', 'My Country'),
  ('childrens_songbook', '211', 'My Dad'),
  ('childrens_songbook', '225', 'My Flag, My Flag'),
  ('childrens_songbook', '273', 'My Hands'),
  ('childrens_songbook', '293', 'My Heart Ever Faithful'),
  ('childrens_songbook', '228', 'My Heavenly Father Loves Me'),
  ('childrens_songbook', '203', 'My Mother Dear'),
  ('childrens_songbook', '120', 'Nephi''s Courage'),
  ('childrens_songbook', '295', 'O Rest in the Lord'),
  ('childrens_songbook', '279', 'Oh, How We Love to Stand'),
  ('childrens_songbook', '48', 'Oh, Hush Thee, My Baby'),
  ('childrens_songbook', '245', 'Oh, What Do You Do in the Summertime?'),
  ('childrens_songbook', '88', 'On a Golden Springtime'),
  ('childrens_songbook', '249', 'Once There Was a Snowman'),
  ('childrens_songbook', '41', 'Once within a Lowly Stable'),
  ('childrens_songbook', '135', 'Our Bishop'),
  ('childrens_songbook', '30b', 'Our Chapel Is a Sacred Place'),
  ('childrens_songbook', '254b', 'Our Door Is Always Open'),
  ('childrens_songbook', '258', 'Our Primary Colors'),
  ('childrens_songbook', '50', 'Picture a Christmas'),
  ('childrens_songbook', '214', 'Pioneer Children Sang As They Walked'),
  ('childrens_songbook', '215', 'Pioneer Children Were Quick to Obey'),
  ('childrens_songbook', '242', 'Popcorn Popping'),
  ('childrens_songbook', '298', 'Prelude in F'),
  ('childrens_songbook', '197b', 'Quickly I''ll Obey'),
  ('childrens_songbook', '241b', 'Rain Is Falling All Around'),
  ('childrens_songbook', '155', 'Remember the Sabbath Day'),
  ('childrens_songbook', '98', 'Repentance'),
  ('childrens_songbook', '27a', 'Reverence'),
  ('childrens_songbook', '31', 'Reverence Is Love'),
  ('childrens_songbook', '26', 'Reverently, Quietly'),
  ('childrens_songbook', '274', 'Roll Your Hands'),
  ('childrens_songbook', '36', 'Samuel Tells of the Baby Jesus'),
  ('childrens_songbook', '196', 'Saturday'),
  ('childrens_songbook', '109', 'Search, Ponder, and Pray'),
  ('childrens_songbook', '108', 'Seek the Lord Early'),
  ('childrens_songbook', '144', 'Shine On'),
  ('childrens_songbook', '253a', 'Sing a Song'),
  ('childrens_songbook', '193', 'Sing Your Way Home'),
  ('childrens_songbook', '47', 'Sleep, Little Jesus'),
  ('childrens_songbook', '267a', 'Smiles'),
  ('childrens_songbook', '238', 'Springtime Is Coming'),
  ('childrens_songbook', '159', 'Stand for the Right'),
  ('childrens_songbook', '278', 'Stand Up'),
  ('childrens_songbook', '37', 'Stars Were Gleaming'),
  ('childrens_songbook', '297', 'Supplication'),
  ('childrens_songbook', '177', 'Teach Me to Walk in the Light'),
  ('childrens_songbook', '178', 'Teacher, Do You Love Me?'),
  ('childrens_songbook', '57', 'Tell Me the Stories of Jesus'),
  ('childrens_songbook', '176', 'Tell Me, Dear Lord'),
  ('childrens_songbook', '10', 'Thank Thee for Everything'),
  ('childrens_songbook', '24', 'Thank Thee, Father'),
  ('childrens_songbook', '20b', 'Thanks to Our Father'),
  ('childrens_songbook', '6', 'Thanks to Thee'),
  ('childrens_songbook', '119', 'The Books in the Book of Mormon'),
  ('childrens_songbook', '116', 'The Books in the New Testament'),
  ('childrens_songbook', '114', 'The Books in the Old Testament'),
  ('childrens_songbook', '156', 'The Chapel Doors'),
  ('childrens_songbook', '77', 'The Church of Jesus Christ'),
  ('childrens_songbook', '112', 'The Commandments'),
  ('childrens_songbook', '208', 'The Dearest Names'),
  ('childrens_songbook', '127', 'The Eighth Article of Faith'),
  ('childrens_songbook', '130', 'The Eleventh Article of Faith'),
  ('childrens_songbook', '194', 'The Family'),
  ('childrens_songbook', '125', 'The Fifth Article of Faith'),
  ('childrens_songbook', '122a', 'The First Article of Faith'),
  ('childrens_songbook', '124', 'The Fourth Article of Faith'),
  ('childrens_songbook', '86b', 'The Golden Plates'),
  ('childrens_songbook', '220', 'The Handcart Song'),
  ('childrens_songbook', '92', 'The Hearts of the Children'),
  ('childrens_songbook', '90', 'Truth from Elijah'),
  ('childrens_songbook', '105', 'The Holy Ghost'),
  ('childrens_songbook', '153', 'The Lord Gave Me a Temple'),
  ('childrens_songbook', '52', 'The Nativity Song'),
  ('childrens_songbook', '128a', 'The Ninth Article of Faith'),
  ('childrens_songbook', '219', 'The Oxcart'),
  ('childrens_songbook', '89', 'The Priesthood Is Restored'),
  ('childrens_songbook', '237', 'The Prophet Said to Plant a Garden'),
  ('childrens_songbook', '72', 'The Sacrament'),
  ('childrens_songbook', '87', 'The Sacred Grove'),
  ('childrens_songbook', '122b', 'The Second Article of Faith'),
  ('childrens_songbook', '126b', 'The Seventh Article of Faith'),
  ('childrens_songbook', '40', 'The Shepherd''s Carol (Round)'),
  ('childrens_songbook', '40b', 'The Shepherd''s Carol'),
  ('childrens_songbook', '126a', 'The Sixth Article of Faith'),
  ('childrens_songbook', '106', 'The Still Small Voice'),
  ('childrens_songbook', '128b', 'The Tenth Article of Faith'),
  ('childrens_songbook', '170', 'The Things I Do'),
  ('childrens_songbook', '123', 'The Third Article of Faith'),
  ('childrens_songbook', '132', 'The Thirteenth Article of Faith'),
  ('childrens_songbook', '131', 'The Twelfth Article of Faith'),
  ('childrens_songbook', '281', 'The Wise Man and the Foolish Man'),
  ('childrens_songbook', '154', 'The Word of Wisdom'),
  ('childrens_songbook', '235', 'The World Is So Big'),
  ('childrens_songbook', '233', 'The World Is So Lovely'),
  ('childrens_songbook', '40a', 'There Was Starlight on the Hillside'),
  ('childrens_songbook', '30a', 'This Is God''s House'),
  ('childrens_songbook', '76', 'This Is My Beloved Son'),
  ('childrens_songbook', '289', 'To a Wild Rose'),
  ('childrens_songbook', '218', 'To Be a Pioneer'),
  ('childrens_songbook', '275b', 'To Get Quiet'),
  ('childrens_songbook', '71', 'To Think about Jesus'),
  ('childrens_songbook', '270', 'Two Happy Feet'),
  ('childrens_songbook', '268', 'Two Little Eyes'),
  ('childrens_songbook', '263', 'We Are Different'),
  ('childrens_songbook', '27b', 'We Are Reverent'),
  ('childrens_songbook', '25a', 'We Bow Our Heads'),
  ('childrens_songbook', '256', 'We Welcome You'),
  ('childrens_songbook', '172', 'We''ll Bring the World His Truth'),
  ('childrens_songbook', '259', 'We''re All Together Again'),
  ('childrens_songbook', '217', 'Westward Ho!'),
  ('childrens_songbook', '201', 'When Grandpa Comes'),
  ('childrens_songbook', '82', 'When He Comes Again'),
  ('childrens_songbook', '103', 'When I Am Baptized'),
  ('childrens_songbook', '157', 'When I Go to Church'),
  ('childrens_songbook', '102', 'When Jesus Christ Was Baptized'),
  ('childrens_songbook', '38', 'When Joseph Went to Bethlehem'),
  ('childrens_songbook', '198b', 'When We''re Helping'),
  ('childrens_songbook', '222', 'Whenever I Think about Pioneers'),
  ('childrens_songbook', '138', 'Where Love Is'),
  ('childrens_songbook', '46', 'Who Is the Child?'),
  ('childrens_songbook', '285', 'You''ve Had a Birthday'),
  ('childrens_songbook', '283', 'Your Happy Birthday')
on conflict (songbook, number) do nothing;
