-- 049_bulk_import_people.sql
--
-- One-time bulk name import (2026-09-10, the user's own explicit
-- request: "I also need to do a one-time name input... I need a way to
-- not duplicate the names as well") -- a deliberate, named exception to
-- this app's own "no bulk import, add people one at a time" policy
-- (see PROJECT_CONTEXT.md's "Adding new people" workflow/policy), not a
-- reversal of it: still name-only, no other PII copied in, just applied
-- as one batch instead of one row at a time, at the user's own request.
--
-- Skips any name already present in `people` (case-insensitive,
-- leading/trailing whitespace ignored) rather than trusting the pasted
-- list not to overlap with what's already there. The 412 names below
-- were checked against each other first (case-insensitively) and have
-- no internal duplicates -- this WHERE NOT EXISTS is purely about
-- overlap with rows that already existed in `people` before this ran.
--
-- Idempotent: re-running this after some of these names already exist
-- (from this migration, or added individually since) only inserts
-- whichever are still missing -- it can never create a second row for
-- a name it already added.
--
-- New people default to attendance_status = 'attending' and
-- active = true (so they show up in assignment pickers immediately) --
-- age_group is left blank, since it can't be reliably guessed from a
-- name alone.

insert into people (name, attendance_status, active)
select v.name, 'attending', true
from (
  values
  ('Chelsea Abrath'),
  ('Quinn Abrath'),
  ('Dianne Katherine Adams'),
  ('Emily Adams'),
  ('Hunter Wayne Adams'),
  ('Mark Stephen Adams'),
  ('Mark Wesley Adams'),
  ('Ashley Alder'),
  ('Chase Todd Alder'),
  ('Daxton Boyce Alder'),
  ('Reagan Ann Alder'),
  ('Jomalyn Claire Arambulo Alitagtag'),
  ('Leah Alitagtag'),
  ('Ben Allen'),
  ('Angelica Mae Amidan'),
  ('Shane Dee Amidan'),
  ('Corey Anderson'),
  ('Emily Anderson'),
  ('Melanie Anderson'),
  ('Karen La Ree Andreasen'),
  ('Michael Andreasen'),
  ('Dee Dee Andreason'),
  ('Amy Attanasio'),
  ('Brandon Attanasio'),
  ('Logan James Attanasio'),
  ('Bret Donald Averett'),
  ('Denae Averett'),
  ('Jessica Barrett'),
  ('Anniston Kate Barton'),
  ('Scott Mitchell Barton'),
  ('Benjamin Beecher'),
  ('Danielle Bennett'),
  ('Joseph T Bennett'),
  ('Lorelei Bennett'),
  ('Weston Ward Bertlshofer'),
  ('Jack Taylor Beutler'),
  ('Savannah Beutler'),
  ('Colten Jared Bingham'),
  ('Shayne Bingham'),
  ('Andrew Bott'),
  ('Kara Bott'),
  ('Kevin Bott'),
  ('Landon Bott'),
  ('Oakley Bott'),
  ('Sierra Bott'),
  ('Zane Bott'),
  ('Khloe Skye Boyack'),
  ('Heidi Brophy'),
  ('Sean Brophy'),
  ('Alex Brown'),
  ('Alex Steven Brown'),
  ('Bryson Brown'),
  ('Eden Brown'),
  ('Erica Brown'),
  ('Kelsey Brown'),
  ('Ronnie Brown'),
  ('Steve Brown'),
  ('Tracy Brown'),
  ('Trevor Brown'),
  ('Tylor Brown'),
  ('Emma Rose Brunson'),
  ('Jacob Brunson'),
  ('Jessica Brunson'),
  ('Shane Brunson'),
  ('Jennifer Bryson'),
  ('Lee Bryson'),
  ('Jodi Butler'),
  ('Lance Butler'),
  ('Lexi Butler'),
  ('Trevor Butler'),
  ('Casey Bybee'),
  ('Heidi Bybee'),
  ('Madelyn Bybee'),
  ('Tatum Bybee'),
  ('Robert Daniel Callihan'),
  ('Danny Cardenas'),
  ('Brody Cardon'),
  ('Corben Cardon'),
  ('Jeremy Cardon'),
  ('Kelly Cardon'),
  ('Lance Cardon'),
  ('Trevor Cardon'),
  ('Zackary Cardon'),
  ('Derek Child'),
  ('Abbigail Skye Cinnamon'),
  ('Darwin Boyd Cochran'),
  ('Wendy Lynn Cochran'),
  ('Cade Coleman'),
  ('Cris Cordero'),
  ('Leizel Cordero'),
  ('Lorenzo Cordero'),
  ('Olga Cordero'),
  ('Roberta Tonie Cores Malcom'),
  ('Kaden Craven'),
  ('Liz Craven'),
  ('Shalynn Cunningham'),
  ('Trace Cunningham'),
  ('Wendy Cunningham'),
  ('Hadleigh Mae Daley'),
  ('Jeremy Daley'),
  ('Lynsie Daley'),
  ('Christopher DeVore'),
  ('Riley DeVore'),
  ('Mitch Drake'),
  ('Trena Drake'),
  ('Trevor Dunn'),
  ('Drex Carl Dutson'),
  ('Krue Dutson'),
  ('McCall Dutson'),
  ('Christine Earl'),
  ('Allison Fausett'),
  ('Ron Francis'),
  ('Sally Francis'),
  ('Kamree Paige Frandsen'),
  ('Karlee Elise Frandsen'),
  ('Kate Marie Frandsen'),
  ('Kyle Wilson Frandsen'),
  ('Merrilee Frandsen'),
  ('Jody Frederiksen'),
  ('Kent Fullmer'),
  ('Sherry Fullmer'),
  ('Ashley Gates'),
  ('Bryce Gates'),
  ('Ellis Gates'),
  ('Kellan Gates'),
  ('Liam Gates'),
  ('Corbin Cade Gatten'),
  ('Aaron Justin Gerlach'),
  ('Jason Benjamin Gerlach'),
  ('Natalie Gerlach'),
  ('Nora Gerlach'),
  ('Pamela Eileen Gerlach'),
  ('Spencer Jason Gerlach'),
  ('Breanne Glismann'),
  ('Kelly M Graham'),
  ('Mike Graham'),
  ('Annie Green'),
  ('Baylie Griffin'),
  ('Dalton Griffin'),
  ('Lyndsey Griffin'),
  ('Nate Griffin'),
  ('Cory Hardman'),
  ('Jeremy Hardman'),
  ('Lucy Hardman'),
  ('Zachary Jacob Hardman'),
  ('Gerald Duane Harrison'),
  ('Curtis Hartey'),
  ('Debbie Hartey'),
  ('Nick Hartey'),
  ('Kate Riley Hedgepeth'),
  ('Hunter Heidrich'),
  ('Mikenzee Heidrich'),
  ('Hailey Lynn Hellewell'),
  ('Joseph Hellewell'),
  ('John Hernandez'),
  ('Kerri Hernandez'),
  ('Isabel Hiatt'),
  ('Jared Hiatt'),
  ('Melisa Hiatt'),
  ('Noah Kevin Hiatt'),
  ('Olivia Hiatt'),
  ('Joyce Lynne Holdeman'),
  ('Lynn Walter Holdeman'),
  ('Carla Honeycutt'),
  ('Amy Marie Honsvick'),
  ('Tyler Honsvick'),
  ('Alaylee Ann Horrocks'),
  ('Dane Horrocks'),
  ('Preston Mathew Horrocks'),
  ('Nerissa Maralit Horton'),
  ('Brittany Howell'),
  ('Russell Howell'),
  ('Ephraim Valentine Hull'),
  ('Michelle Hull'),
  ('River Selima Hull'),
  ('Dane Huntsman'),
  ('Annessa Hyllested'),
  ('Cadence Marie Hyllested'),
  ('Erik Hyllested'),
  ('Kieler Hyllested'),
  ('Tage Hyllested'),
  ('Mia Ivers'),
  ('Angel Jaeger'),
  ('Samantha Jaeger'),
  ('Taylorlynn Francise Jaeger'),
  ('Devin Jenkins'),
  ('Stacey Jenkins'),
  ('Erica Jolley'),
  ('Jace Eric Jones'),
  ('Kaylie Jones'),
  ('Joyce Kearl'),
  ('Shawn Kearl'),
  ('Steven Michael Kearl'),
  ('Eric Kelley'),
  ('Sally Ann Kelley'),
  ('Addelyn Jane King'),
  ('Amber King'),
  ('Carlee King'),
  ('Curt King'),
  ('Nicole King'),
  ('Denise Krauss'),
  ('Kasey Allen Krauss'),
  ('Kody Krauss'),
  ('Kolton John Krauss'),
  ('Walter Krauss'),
  ('Dean Kreger'),
  ('Teresa Kreger'),
  ('Cedrick Le Tendre'),
  ('Dena Le Tendre'),
  ('Karleen Annick Le Tendre'),
  ('Matisse Le Tendre'),
  ('Philippe Le Tendre'),
  ('Talen Le Tendre'),
  ('Brenda Lewis'),
  ('Jaylen Linsley'),
  ('Tanner Linsley'),
  ('Darcie Liptrot'),
  ('Kloe Liptrot'),
  ('Kru Liptrot'),
  ('Steven Liptrot'),
  ('Hayden Malloy Lopez'),
  ('Sara Lopez'),
  ('Theresa Anne Lopez'),
  ('Kimball Ludlow'),
  ('Mark Ludlow'),
  ('Rosann Ludlow'),
  ('Benjamin Lund'),
  ('Clark Lund'),
  ('Holly Lund'),
  ('Jackson Lund'),
  ('Dan Merkling'),
  ('Marlene Merkling'),
  ('Braxton Merritt'),
  ('Davis Merritt'),
  ('Heidi Merritt'),
  ('Preston William Merritt'),
  ('Scott Merritt'),
  ('Chaylyn Miles'),
  ('Colton Miles'),
  ('Kelsey Jean Miles'),
  ('Len Millgate'),
  ('Shauna Millgate'),
  ('Ally Elizabeth Milne'),
  ('Cindy Lee Milne'),
  ('Jacob Robert Milne'),
  ('Jason Michael Milne'),
  ('Robert Gene Milne'),
  ('Samantha Jo Lynn Milne'),
  ('Boston Misner'),
  ('Bridger Misner'),
  ('Oaklee Misner'),
  ('David Moyes'),
  ('Jarom Musgrove'),
  ('Kaitlyn Musgrove'),
  ('Elisabeth Nebeker'),
  ('Elise Nemrow'),
  ('JJ Nemrow'),
  ('Joe Nemrow'),
  ('Rachel Elaine Nemrow'),
  ('Claire Newbold'),
  ('Eli Nicholas Newbold'),
  ('Henry Newbold'),
  ('Lorie Newbold'),
  ('Nick Newbold'),
  ('Catherine Rose Nye'),
  ('Amber Olney'),
  ('Ayden Olney'),
  ('Evyn Olney'),
  ('Grayson Olney'),
  ('Jacob Olney'),
  ('Shyler Olney'),
  ('Derrick Olsen'),
  ('Hajnalka Telegdi Olsen'),
  ('Hanna Olsen'),
  ('Ron Osborn'),
  ('Elijah Bruce Packer'),
  ('Kimberly Packer'),
  ('Tandon Packer'),
  ('Scott Larry Parker'),
  ('Daniel Peterson'),
  ('Janice Pierce'),
  ('Wendy Pop'),
  ('Jared V Preslar'),
  ('Ryan Quick'),
  ('Shelese Quick'),
  ('Tristen Quick'),
  ('Ashley Rappleye'),
  ('Jason Rappleye'),
  ('Nixon J Rappleye'),
  ('Dean Rasband'),
  ('Holly Rasband'),
  ('Chrystal Reid'),
  ('Josh Retallick'),
  ('Kolian Richard Rogers'),
  ('Sabrina Leanne Rogers'),
  ('Ginny Rouse'),
  ('Ronnie Rouse'),
  ('Jenny Schow'),
  ('Michael Schow'),
  ('Kelly Jon Sellers'),
  ('Peyton Lee Sellers'),
  ('Suzanne Lee Sellers'),
  ('Tristan David Sellers'),
  ('Lindsey Seright'),
  ('Tyson Seright'),
  ('Lisa Ann Sherant'),
  ('Kevin Lee Slisze'),
  ('Brynna May Smith'),
  ('Jason Smith'),
  ('Kathy Smith'),
  ('Mallory Rhen Smith'),
  ('Naomi Faith Smith'),
  ('Anna Snarr'),
  ('Becky Snarr'),
  ('Joshua Ryan Snarr'),
  ('Peter Snarr'),
  ('Ryan Snarr'),
  ('Alexander Daniel Solomon'),
  ('Lauren Reay Solomon'),
  ('Bryce Southworth'),
  ('Jacque Southworth'),
  ('Matthew Stainbrook'),
  ('Rachel Staker'),
  ('Shawn Staker'),
  ('Danielle Steggell'),
  ('James Steggell'),
  ('Beckam Stewart'),
  ('Travis Stewart'),
  ('Luke Jacob Swensen'),
  ('Michelle Swensen'),
  ('Holly Tanner'),
  ('Keith Tanner'),
  ('Michelle Tanner'),
  ('Ryan Tanner'),
  ('Savannah Tanner'),
  ('Ethan Taylor'),
  ('Kristie Thorne Taylor'),
  ('Wayne Taylor'),
  ('Becky Thorne'),
  ('Brandon Thorne'),
  ('Scott Thorne'),
  ('Shelly Thorne'),
  ('Tana Thorne'),
  ('Kathy Thurgood'),
  ('Paul Thurgood'),
  ('Alyssa Topham'),
  ('Chris Topham'),
  ('Brandon VanderStappen'),
  ('Bree VanderStappen'),
  ('David VanderStappen'),
  ('Dawson VanderStappen'),
  ('Destynee VanderStappen'),
  ('Donelle VanderStappen'),
  ('Hailey Lynn Vasilenko'),
  ('Chuck Vaughan'),
  ('Lori Vaughan'),
  ('Brandie Lorraine Wakefield'),
  ('Navee Brynn Wakefield'),
  ('Tyson Wakefield'),
  ('Tawni Waldram'),
  ('Bronco Walker'),
  ('Emery Walker'),
  ('Kypton Walker'),
  ('McKehl Walker'),
  ('Zach Walker'),
  ('Craig Warburton'),
  ('Eric Warburton'),
  ('Susy Warburton'),
  ('Kimberly Dawn Waters'),
  ('Henry Nathan Weiss'),
  ('Kassidy Weiss'),
  ('Ashlyn Welch'),
  ('Holden Welch'),
  ('Daniel Jay Wheelwright'),
  ('Jarrod Wiberg'),
  ('Briggs Wieboldt'),
  ('Ivan Wieboldt'),
  ('Lisa Wieboldt'),
  ('Tom Wieboldt'),
  ('Zane Wieboldt'),
  ('Amy Nicole Wilkinson'),
  ('Anne Wilkinson'),
  ('Karen Amber Wilkinson'),
  ('Maud Mary Wilkinson'),
  ('Niki Rochelle Wilkinson'),
  ('Ronald Allen Wilkinson'),
  ('Breeana Williams'),
  ('Jeff Williams'),
  ('Daria Wing'),
  ('Gavin Wycherly'),
  ('Toni Wycherly'),
  ('Brigg Young'),
  ('Bryce Aroet Young'),
  ('Emery Young'),
  ('Malynn Patricia Young'),
  ('Marie Young'),
  ('Mark Young'),
  ('Beckham Zaugg'),
  ('Corbin Zaugg'),
  ('Darin Zaugg'),
  ('Jennifer Zaugg'),
  ('Parker Zaugg'),
  ('Pat Zaugg'),
  ('Ray Zaugg'),
  ('Zander Zaugg'),
  ('Brent Zimmerman'),
  ('Christian Carter Zimmerman'),
  ('Madilyn Christine Zimmerman'),
  ('McKenzie Zimmerman'),
  ('Melanie Zimmerman'),
  ('Zachary Brent Zimmerman'),
  ('Brittany Zoltz')
) as v(name)
where not exists (
  select 1 from people p where lower(trim(p.name)) = lower(trim(v.name))
);
